apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app-1-hpa
  namespace: development
spec:
  maxReplicas: 3 # define max replica count
  minReplicas: 1  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-1
  targetCPUUtilizationPercentage: 50 # target CPU utilization